### ISSUE TITLE
Please support dotnet core.

### ISSUE THREAD

**Issue by mthamil** [destructurama/by-ignoring#1]
I have a fairly large response object I want to log, but it does contain sensitive information I want to exclude. I don't control the code of the object since it is a generated SOAP client, otherwise I'd try to use the attribute package. I just tried to install this into a dotnet core 1.1 app and received the following error:

> Package Destructurama.ByIgnoring 1.0.4 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Destructurama.ByIgnoring 1.0.4 supports: portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)

**Comment by nblumhardt** [comment]
Thanks for the note @mthamil 👍 

I'm not able to work on a PR for this at the moment, but we'd gladly accept a contribution to add .NET Standard support if anyone else can.

**Comment by mthamil** [comment]
Sure, I may give it a shot.

On Oct 3, 2017 7:03 PM, Nicholas Blumhardt <notifications@github.com> wrote:

Thanks for the note @mthamil<https://github.com/mthamil> 👍

I'm not able to work on a PR for this at the moment, but we'd gladly accept a contribution to add .NET Standard support if anyone else can.

**Comment by mthamil** [comment]
Ah, thanks!

**Comment by mthamil** [comment]
So, for some reason there is no new version of this package on the nuget gallery. It appears the package was not pushed during build because it was for the dev branch.

**Comment by nblumhardt** [comment]
Thanks for the note. Think I've fixed publishing now, will keep an eye on the build. Cheers!

**Comment by nblumhardt** [comment]
Published now 👍

**Comment by danjohnso** [comment]
I think this publish is broken.  The latest pre-release does not have the extensions in it but the stable version does not support .net standard
