### ISSUE TITLE
`dev` branch builds are broken

### ISSUE THREAD

**Issue by nblumhardt** [destructurama/by-ignoring#12]
Unsure of the cause, may need an SDK update:

https://ci.appveyor.com/project/Destructurama/by-ignoring/builds/41354899

**Comment by sungam3r** [comment]
https://github.com/NuGet/Home/issues/7414

**Comment by SimonCropp** [comment]
at build time, i have been explicitly installing the version defined in global json 
https://github.com/VerifyTests/Verify/blob/main/src/appveyor.yml#L7-L21

so moving forward, i can change the sdk with no dependency on appveyor

**Comment by sungam3r** [comment]
Or switch to GitHub Actions.

**Comment by sungam3r** [comment]
Rel - #21
