### ISSUE TITLE
Request to support latest version of Serilog >=3.0.1

### ISSUE THREAD

**Issue by Vijay-Kumar-intelliflo** [destructurama/by-ignoring#16]
As of now there is a dependency of Destructurama.ByIgnoring 1.1.0 -> Serilog (>= 2.8.0 && < 3.0.0), could the library be updated to support Serilog >=3.0.1

**Comment by jaminman** [comment]
I too ran into this issue and have created a [PR](https://github.com/destructurama/by-ignoring/pull/15) to solve this issue.  Once it has been reviewed and approved, it should update the NuGet package.

**Comment by Vijay-Kumar-intelliflo** [comment]
@jaminman -There seems to be a review comment in your PR, could you please check.

**Comment by jaminman** [comment]
Thank you @Vijay-Kumar-intelliflo.  I made the changes requested made by @nblumhardt.

**Comment by jaminman** [comment]
@nblumhardt, Thank you for merging the code updates.  Do you know what kicks off the build script to create the NuGet package?  Is it automatic or manual?

**Comment by nblumhardt** [comment]
Hi @jaminman - this is normally automatic, but the publishing key had expired. Updated now, should be a new build there shortly. Thanks!

**Comment by Vijay-Kumar-intelliflo** [comment]
Hi @jaminman - Thanks you for making the changes. Is the new version of NuGet package has been released?

**Comment by jaminman** [comment]
@Vijay-Kumar-intelliflo, I see there is a dev version (pre-release) out on [NuGet](https://www.nuget.org/packages/Destructurama.ByIgnoring/1.1.1-dev-00062).  I am not sure what needs to happen to get it into a stable release format.  @nblumhardt or @sungam3r, what can we do to help get this promoted to release worthy on nuget.org and close this issue?

**Comment by nblumhardt** [comment]
https://github.com/destructurama/by-ignoring/pull/17 is open now for the release; feedback on how the current `-dev` package is going would help move this along. Thanks!

**Comment by Vijay-Kumar-intelliflo** [comment]
@nblumhardt , @sungam3r  Apologies for the delay in confirming, the dev package is working correctly with the Serilog 3.0.1. Could you please release the Package.

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/Destructurama.ByIgnoring/2.0.0 was realesed. Closed.

**Comment by Vijay-Kumar-intelliflo** [comment]
Thank you !!
