### ISSUE TITLE
Switch to GitHub Action

### ISSUE THREAD

**Issue by sungam3r** [destructurama/by-ignoring#21]
I propose to switch to GitHub Action as a more robust CI ecosystem.

**Comment by nblumhardt** [comment]
@sungam3r sounds like it will make the project easier to keep updated in the presence of ever-churning NuGet API keys 👍 

What's needed to kick this off? (I haven't set up Actions in a while :-))

**Comment by sungam3r** [comment]
@nblumhardt I need permissions to configure repo settings.

**Comment by nblumhardt** [comment]
Thanks @sungam3r; I've updated permissions so that you should have admin access to the `destructurama/*` repos now.

**Comment by nblumhardt** [comment]
`NUGET_AUTH_TOKEN` is now set organization-wide :tada: 

Apologies as usual for the slow turnaround from me, glad you're pushing ahead with everything here :bow:

**Comment by sungam3r** [comment]
Thanks.
