### ISSUE TITLE
Setup CodeCov

### ISSUE THREAD

**Issue by sungam3r** [destructurama/by-ignoring#30]
![изображение](https://github.com/destructurama/by-ignoring/assets/21261007/439f95c7-25f2-4a91-98a1-a12a3b92f76d)

**Comment by sungam3r** [comment]
https://docs.codecov.com/docs/quick-start

![изображение](https://github.com/destructurama/by-ignoring/assets/21261007/54eb8cec-0d22-4a52-8c70-b64aa55db774)


![изображение](https://github.com/destructurama/by-ignoring/assets/21261007/6429e088-d569-47cb-833a-2a2b969aab17)

@nblumhardt I think I'm still have no admin permissions. I think only owners can accept such requests. I'm a member of destructurama org but not an owner.

**Comment by nblumhardt** [comment]
I've authorized CodeCov now, let me know if it works correctly for you 👍

**Comment by sungam3r** [comment]
I'm trying to
![изображение](https://github.com/destructurama/by-ignoring/assets/21261007/9748ee6e-0840-4393-908a-ea8c9f0b6597)
and getting
![изображение](https://github.com/destructurama/by-ignoring/assets/21261007/c5beb722-f8f2-44f4-a29c-78cffe23f7de)

**Comment by nblumhardt** [comment]
Odd, I just went to that page and I see:

![image](https://github.com/destructurama/by-ignoring/assets/342712/4b8b71ce-1a32-4fee-85e0-2f754c8be412)

Still hitting the same problem?

**Comment by sungam3r** [comment]
Hmm. Now I can access all org repos from codecov. I've added repo token and updated badge.
![изображение](https://github.com/destructurama/by-ignoring/assets/21261007/c645f52a-10d9-4d2e-9b11-fe46312edbdc)

See #44.

**Comment by sungam3r** [comment]
Done. Thanks!
![изображение](https://github.com/destructurama/by-ignoring/assets/21261007/eccf3074-e624-49d8-b694-4c256fcee99c)
