### ISSUE TITLE
Release version to nuget

### ISSUE THREAD

**Issue by joelweiss** [destructurama/by-ignoring#5]
Any chance of releasing a Release version to [nuget](https://www.nuget.org/packages/Destructurama.ByIgnoring/1.1.0-dev-00019)?

Much appreciated.

**Comment by mason-mcglothlin** [comment]
Any updates on this?

The latest non-prerelease version wants Serilog 1.X, so if we try to use it with Serilog 2.X it adds binding redirects, and I try to avoid those when I can. So we're taking a dependency on a prerelease package, which we're kind of loathe to do.

**Comment by sungam3r** [comment]
Relates to #6

**Comment by joelweiss** [comment]
Thanks @nblumhardt
