### ISSUE TITLE
Seems like the nuget package is not compatible with .NET Core 3.1?

### ISSUE THREAD

**Issue by triple-vee** [destructurama/by-ignoring#7]
Happy to contribute if you need a compatible version.

**Comment by sungam3r** [comment]
What do you mean _not compatible_ ? https://www.nuget.org/packages/Destructurama.ByIgnoring/1.1.0-dev-00026

**Comment by feitzi** [comment]
Why is this in a prerelease version? Are there any problems with that version, or why is this not released for more than a year?

**Comment by sungam3r** [comment]
I don't know, ping @nblumhardt .

**Comment by nblumhardt** [comment]
Just got behind :-) ... opened release pr #8.
